/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        headline: ["Newsreader", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#131313",
        foreground: "#e5e2e1",
        "primary-fixed": "#5d5f5f",
        "on-error-container": "#ffdad6",
        "secondary-container": "#474746",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#adabaa",
        "on-tertiary-container": "#000000",
        "on-primary-container": "#000000",
        "tertiary-container": "#929090",
        "primary-alt": "#ffffff",
        "error": "#ffb4ab",
        "on-primary-fixed": "#ffffff",
        "on-secondary-fixed-variant": "#3c3b3b",
        "primary-fixed-dim": "#454747",
        "on-surface-variant": "#c6c6c6",
        "on-tertiary-fixed": "#ffffff",
        "surface": "#131313",
        "surface-container-highest": "#353534",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#e4e2e1",
        "surface-tint": "#c6c6c7",
        "inverse-primary": "#5d5f5f",
        "surface-variant": "#353534",
        "on-secondary-container": "#e5e2e1",
        "on-primary-fixed-variant": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#5f5e5e",
        "tertiary-fixed-dim": "#474747",
        "surface-container-high": "#2a2a2a",
        "on-primary": "#1a1c1c",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "tertiary": "#e4e2e1",
        "on-tertiary": "#1b1c1c",
        "on-error": "#690005",
        "on-secondary": "#1c1b1b",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "secondary-alt": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#c8c6c5",
        "outline-variant": "#474747",
        "outline": "#919191",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
